### ISSUE TITLE
Inline Edit for HTML in Typescript

### ISSUE THREAD

**Issue by divramod** [AndrewRadev/inline_edit.vim#18]
Hey Andrew, 

thx for your nice work.

I'd like to use InlineEdit for a ionic 2 / angular 2 / typescript project.

I have a Typescript file that looks like that:

import {Modal, NavController, ViewController} from 'ionic-angular';
import {Page} from 'ionic-angular';

```
@Page({
  template: `
    <ion-navbar *navbar>
        <ion-title middle>Device Information</ion-title>
        <ion-buttons end>
          <button (click)="close()" left>
            <ion-icon name="close"></ion-icon>
          </button>
        </ion-buttons>
    </ion-navbar>
    <ion-content>
      <ion-row>
        <ion-col width-20>
          <ion-card>
            <ion-card-header>
              Device uuid
            </ion-card-header>
            <ion-card-content>
                {{deviceUuid}}
            </ion-card-content>
          </ion-card>
        </ion-col>
      </ion-row>
    </ion-content>
  `
})
export class DeviceModal {

  private deviceUuid: string;

  constructor(
      private viewCtrl: ViewController
  ) {
      this.deviceUuid = device.uuid;

  }
  
  close() {
    this.viewCtrl.dismiss();
  }
}
```
In the Template Part i like to InlineEdit html.
I can use it with visual selecting it but can you give me a hint how to automate the selection between the ticks?

**Comment by AndrewRadev** [comment]
I don't use typescript, so I'm not sure if this is the right kind of pattern, but here's something that works with your example:

``` vim
let g:inline_edit_patterns = [
      \   {
      \     'main_filetype': 'typescript',
      \     'sub_filetype': 'html',
      \     'indent_adjustment': 1,
      \     'start': '^\s*template: `\s*$',
      \     'end': '^\s*`\s*$'
      \   }
      \ ]
```

The `start` and `end` keys are the start regex and end regex that the plugin looks for. For the start, I've tried to capture the entire `template: ` key with the backtick, but maybe it's not always "template"? I've also added `^\s*` and `\s*$` to anchor the patterns to the beginning and end of the line (so the end pattern, for example, is "a single backtick, surrounded by only whitespace").

I've tried to describe it in the help docs, try `:help inline-edit-extending`. Let me know if you're still having trouble getting it to work.

**Comment by AndrewRadev** [comment]
Since it seems like this should do the trick for you, I'll go ahead and close the issue. Feel free to reopen if you have more questions, or problems with the method. I also wouldn't mind making it a built-in, but I'd need to know what the "generic" way of describing templates in this language/framework is.
