### ISSUE TITLE
Add support for Vue files

### ISSUE THREAD

**Issue by fvictorio** [AndrewRadev/inline_edit.vim#19]
Vue [single file components](https://vuejs.org/v2/guide/single-file-components.html) are files that contain HTML, Javascript and CSS (each one under a different tag). For example:

```vue
<template>
  <div>
    {{ value }}
  </div>
</template>

<script>
export default {
  state: {
    value: 42
  }
}
</script>

<style>
div {
  font-weight: bold;
}
</style>
```

So, they are pretty much HTML with a convention.

Inline_edit works fine for the JS and CSS (if the filetype includes HTML), but obviously it doesn't for the content of `<template>`.

Working with .vue files in vim has been a pain (even with all the help from [vim-vue](https://github.com/posva/vim-vue)) and I think inline_edit would be great for this use case.

I'll give it a try to add the support myself, but I wanted to open the issue anyway in case I can't do it (and to know if you are willing to add this feature).

Thanks!

**Comment by AndrewRadev** [comment]
I'm open to adding the functionality, yes. I've put some information about extending the plugin in [`:help inline-edit-extending`](https://github.com/AndrewRadev/inline_edit.vim/blob/4a2ad9a1850ee009f687090bd33b4d7fdfe2d36b/doc/inline_edit.txt#L186). That's for extending the plugin locally, but if you'd like to make a PR, that's a good starting point.

A good sample for you would be the css or javascript support: https://github.com/AndrewRadev/inline_edit.vim/blob/4a2ad9a1850ee009f687090bd33b4d7fdfe2d36b/plugin/inline_edit.vim#L61-L67. It should be enough to copy one of those and make some minor adjustments (`main_filetype` should be "vue", for instance). You might also like to add "vue" in the list of html-like filetypes: https://github.com/AndrewRadev/inline_edit.vim/blob/4a2ad9a1850ee009f687090bd33b4d7fdfe2d36b/plugin/inline_edit.vim#L90-L91. This will let you use `script` and `style` tags without setting the filetype to `vue.html` (although that's a useful way to get goodies from both filetypes anyway).

If you feel underprepared to make the change, let me know, but I would be happy to merge a PR if you're interested in learning and building it yourself :).

**Comment by fvictorio** [comment]
Awesome, I'll give it a try. Thanks!
