### ISSUE TITLE
Inline editor doesn't like swapfiles

### ISSUE THREAD

**Issue by MartinAskestad** [AndrewRadev/inline_edit.vim#30]
When activating the inline editor and having swapfiles turned on in Vim, you get an angry message. But the editor seems to open just fine and works as expected. It's just when the editor opens you get this message.

![inline_edit_swapfile](https://user-images.githubusercontent.com/9462004/206890715-3e951ba7-097d-4cc0-9caf-07ee7280c1b9.gif)

**Comment by AndrewRadev** [comment]
I turned on `swapfile` and I can see the file being created, but I'm not getting that error. Do you have other settings in your config that could affect swapfiles, like a `directory` setting? Could you also report what you have set for `g:inline_edit_proxy_type`?

That said, I added `noswapfile` to the proxy buffer, so if you pull from git, it might just work. Let me know.

**Comment by MartinAskestad** [comment]
My directory setting is `set directory-=.`, and your change fixed it. Thank you.
