### ISSUE TITLE
[feat] Support for inline edit ranges specified with both line number and column

### ISSUE THREAD

**Issue by lervag** [AndrewRadev/inline_edit.vim#32]
Currently, it seems inline_edit only support ranges based on line numbers. E.g., I want to add inline_edit support for sql strings in a project I'm working on. It's a scala code where there's a lot cases like this:

```scala
    sql"""SELECT id, foo, bar
          FROM schema.table
          WHERE id = $id"""
      .queryBy(row => ???)
```

I've tried to add support with something like this:

```lua
        {
          main_filetype = "scala",
          sub_filetype = "sql",
          indent_adjustment = 1,
          start = [[\(sql\|SQL\)"""]],
          ["end"] = [["""]],
        },
```

That won't work, because the `SELECT ...` and `WHERE ...` are on the same lines as the start and end patterns. I read the docs and it seems there is currently no way to handle this scenario.

Would it be possible to add an option to make the start and end include a column specifier, such that I could match the text from after the start pattern on the same line until just before the end pattern?

**Comment by AndrewRadev** [comment]
It should be possible, I'll try to implement some method of specifying it, see if I run into issues.

**Comment by lervag** [comment]
Great! Thanks for the quick reply!

**Comment by AndrewRadev** [comment]
I've created a branch, [inline-patterns](https://github.com/AndrewRadev/inline_edit.vim/tree/inline-patterns), where I implemented support for both of these examples:

```scala
something = sql"""SELECT id, foo, bar
                  FROM schema.table
                  WHERE id = $id"""
              .queryBy(row => ???)

something = sql"""
  SELECT id, foo, bar
  FROM schema.table
  WHERE id = $id
"""
.queryBy(row => ???)
```

In the most basic test, both of these work, but I wouldn't be surprised if there are issues, definitely consider it an initial attempt. The config looks like this, but it's added in the branch, so it should work out of the box:

```vim
call add(g:inline_edit_patterns, #{
      \ main_filetype:     "scala",
      \ sub_filetype:      "sql",
      \ indent_adjustment: 1,
      \ include_margins:   1,
      \ start:             '\(sql\|SQL\)"""',
      \ end:               '"""',
      \ })
```

The parameter is `include_margins`, it might turn out that it's unnecessary, but I need to experiment, write some tests, too, and I'll see when I can get around to it. Happy for other ideas on naming.

For now, I'd appreciate it if you played around with it whenever you can and reported, no hurry on when.

**Comment by lervag** [comment]
Thanks! This seems to work very well and is already useable!

I think `include_margins` is an ok parameter name. Another alternative could be `linewise`. If it is true, then the start and end patterns specify the line number boundaries, but if it is false, then the start and end patterns indicate line and column boundaries. Not sure if it is a better name.

I've noticed a couple of problems:

* I get an error sometimes after doing `:wq` in an inlinedit-buffer:

    ![image](https://github.com/AndrewRadev/inline_edit.vim/assets/998898/d9c1c210-3a26-4213-b3ae-8b42251cb206)

    When I press enter to continue, it seems everything worked well.

* If I edit an expression that fits on a single line, the end pattern seems to fail. An example where it fails for me:

    ```scala
    SQL"""SELECT id, name FROM foo""".as(parser.*)
    ```

* Perhaps a hard one: I work in a code base where there is a nasty mix of the "inline" variants and the "linewise" variants. With `include_margins` active, the following example fails:

    ```scala
    SQL"""
      SELECT id, name
      FROM studier.teaching_location
      WHERE id = any(${ids.map(x => x: java.lang.Long)})
    """
    ```

    I.e., if I edit it with inline edit, I notice the edit buffer has a final line. If I save, the final `"""` will be deindented.

By the way: The combination of inline-edit and vim-dadbod is really a great match!

**Comment by AndrewRadev** [comment]
> By the way: The combination of inline-edit and vim-dadbod is really a great match!

Happy to hear, thank you for the kind words :).

I think I managed to fix all of these bugs, but let me know if I've missed a case and/or if you find any more. I put the example cases in tests, so if you don't run into more bugs in a week or two, I could do another code pass, then merge the branch and handle follow-up issues later.

**Comment by lervag** [comment]
Thanks! I've tested your updates, and now it seems to work very well! I'll let you know if I find any other bugs, but I've tested in on several variants now and all of them worked as expected!

**Comment by AndrewRadev** [comment]
Merged the branch, so I'll close this issue for now. Let me know if you run into problems.

**Comment by lervag** [comment]
Thanks!
